repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        # exclude:
      - id: trailing-whitespace
        # exclude:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: [--fix]
        # exclude:
      - id: ruff-format
        # exclude:

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.20
    hooks:
      - id: uv-lock
